
dist: bionic
language: python
git:
  depth: 1
matrix:
  include:
    - python: 3.9
      os: linux
      env:
        - RUN_COVERAGE=true

    - python: 3.6
      os: linux
      env:
        - RUN_COVERAGE=false
install:
  - pip install coverage
  - pip install .
cache:
  - pip
script:
  - if [ "$RUN_COVERAGE" == true ];
    then
        coverage run -m abcpytools.tests;
        coverage report --include="./abcpytools";
    else
        python -m abcpytools.tests;
    fi
